using Microsoft.CodeAnalysis;
using static SOConstantsGenerators.Utilities;

namespace SOConstantsGenerators
{
    [Generator]
    public class OutputFolderFieldGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (syntaxNode, _) => IsTargetNode(syntaxNode),
                    transform: static (context, _) => GetSOInfo(context));

            context.RegisterSourceOutput(provider, Generate);
        }

        private static void Generate(SourceProductionContext context, SOInfo info)
        {
            GenerateOutputFolderField(context, info);
        }

        private static void GenerateOutputFolderField(SourceProductionContext context, SOInfo soInfo)
        {
            var sourceCode = $@"// <auto-generated />
using UnityEngine;
using UnityEditor;

namespace {soInfo.Namespace}
{{
    public partial class {soInfo.Name}
    {{
        [Header(""SO Constants Generator"")]
        public DefaultAsset OutputFolder;
    }}
}}
";

            context.AddSource($"{soInfo.Namespace}.{soInfo.Name}.g.cs", sourceCode);
        }

    }

}
